receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: prometheus:8889
    namespace: default
processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
      processors: [batch]
    metrics:
      receivers: [prometheus]
      exporters: [logging]
      processors: [batch]